const HERO = {"en_sub": "सनातन धर्म · The Eternal Order", "en_desc": "A comprehensive guide to the world's most ancient living wisdom tradition — its vast scriptural universe, philosophical schools, cosmological frameworks, and the profound truths that no single religion can contain. This is the tradition that predates the word \"Hindu,\" the tradition that calls itself <em>eternal</em>.", "gu_sub": "सनातन धर्म · શાશ્વત ધર્મ", "gu_desc": "વિશ્વની સૌથી પ્રાચીન જીવંત જ્ઞાન-પ્રણાલીનો સર્વગ્રાહી માર્ગદર્શ — તેના વિશાળ ધર્મગ્રંથ-સૃષ્ટિ, દાર્શનિક વિચારધારાઓ, બ્રહ્માંડ-વૈજ્ઞાનિક ઢાંચાઓ અને તે ગહન સત્યો, જેમને કોઈ એક ધર્મ સ્વરૂપ ધારણ કરી શકતો નથી. આ એ પ્રણાલી છે જે \"હિન્દુ\" શબ્દ પ્રચલિત થવા પહેલાંથી છે — જે પોતાને શાશ્વત કહે છે."};

/* ═══════════ Verse of the Day — rotates daily on the home screen ═══════════
   Well-attested verses only; citations conservative. */
const VERSES = [
  { deva: 'एकं सत् विप्रा बहुधा वदन्ति',
    en: 'Truth is one; the wise call it by many names.',
    gu: 'સત્ય એક છે; જ્ઞાનીઓ તેને અનેક નામે કહે છે.',
    cite: 'ṚGVEDA 1.164.46' },
  { deva: 'कर्मण्येवाधिकारस्ते मा फलेषु कदाचन',
    en: 'Your right is to the action alone, never to its fruits.',
    gu: 'કર્મ પર જ તારો અધિકાર છે, ફળ પર કદી નહીં.',
    cite: 'BHAGAVAD GĪTĀ 2.47' },
  { deva: 'समत्वं योग उच्यते',
    en: 'Evenness of mind is called yoga.',
    gu: 'મનની સમતા એ જ યોગ કહેવાય છે.',
    cite: 'BHAGAVAD GĪTĀ 2.48' },
  { deva: 'असतो मा सद्गमय । तमसो मा ज्योतिर्गमय',
    en: 'From the unreal lead me to the real; from darkness lead me to light.',
    gu: 'અસત્યમાંથી મને સત્ય તરફ લઈ જા; અંધકારમાંથી પ્રકાશ તરફ.',
    cite: 'BṚHADĀRAṆYAKA UPANIṢAD 1.3.28' },
  { deva: 'सत्यमेव जयते नानृतम्',
    en: 'Truth alone triumphs, not falsehood.',
    gu: 'સત્યનો જ જય થાય છે, અસત્યનો નહીં.',
    cite: 'MUṆḌAKA UPANIṢAD 3.1.6' },
  { deva: 'अहिंसा परमो धर्मः',
    en: 'Non-harming is the highest dharma.',
    gu: 'અહિંસા પરમ ધર્મ છે.',
    cite: 'MAHĀBHĀRATA' },
  { deva: 'वसुधैव कुटुम्बकम्',
    en: 'The whole earth is one family.',
    gu: 'આખી પૃથ્વી એક પરિવાર છે.',
    cite: 'MAHĀ UPANIṢAD 6.71' },
  { deva: 'तत् त्वम् असि',
    en: 'That thou art.',
    gu: 'તે તું છે.',
    cite: 'CHĀNDOGYA UPANIṢAD 6.8.7' },
  { deva: 'अहं ब्रह्मास्मि',
    en: 'I am Brahman.',
    gu: 'હું બ્રહ્મ છું.',
    cite: 'BṚHADĀRAṆYAKA UPANIṢAD 1.4.10' },
  { deva: 'सर्वे भवन्तु सुखिनः सर्वे सन्तु निरामयाः',
    en: 'May all beings be happy; may all be free from illness.',
    gu: 'સૌ સુખી થાઓ; સૌ નિરોગી રહો.',
    cite: 'ŚĀNTI MANTRA' },
  { deva: 'उद्धरेदात्मनात्मानं नात्मानमवसादयेत्',
    en: 'Lift yourself by your own self; do not let the self sink.',
    gu: 'પોતાના વડે જ પોતાનો ઉદ્ધાર કર; પોતાને પડવા ન દે.',
    cite: 'BHAGAVAD GĪTĀ 6.5' },
  { deva: 'श्रद्धावाँल्लभते ज्ञानम्',
    en: 'The one with faith attains knowledge.',
    gu: 'શ્રદ્ધાવાનને જ્ઞાન મળે છે.',
    cite: 'BHAGAVAD GĪTĀ 4.39' },
  { deva: 'यदा यदा हि धर्मस्य ग्लानिर्भवति भारत',
    en: 'Whenever dharma declines, O Bhārata, I bring myself forth.',
    gu: 'જ્યારે જ્યારે ધર્મની ગ્લાનિ થાય છે, હે ભારત, ત્યારે હું પ્રગટ થાઉં છું.',
    cite: 'BHAGAVAD GĪTĀ 4.7' },
  { deva: 'आगमापायिनोऽनित्यास्तांस्तितिक्षस्व भारत',
    en: 'They come and go, impermanent; endure them, O Bhārata.',
    gu: 'સુખ-દુઃખ આવે છે ને જાય છે, અનિત્ય છે; તેમને સહી લે, હે ભારત.',
    cite: 'BHAGAVAD GĪTĀ 2.14' },
  { deva: 'विद्या ददाति विनयम्',
    en: 'Knowledge gives humility.',
    gu: 'વિદ્યા વિનય આપે છે.',
    cite: 'HITOPADEŚA' },
  { deva: 'धर्मो रक्षति रक्षितः',
    en: 'Dharma protects those who protect it.',
    gu: 'ધર્મનું રક્ષણ કરનારનું ધર્મ રક્ષણ કરે છે.',
    cite: 'MANUSMṚTI 8.15' },
  { deva: 'आत्मनः प्रतिकूलानि परेषां न समाचरेत्',
    en: 'Do not do to others what would harm your own self.',
    gu: 'જે પોતાને પ્રતિકૂળ લાગે, તે બીજા સાથે ન કરવું.',
    cite: 'MAHĀBHĀRATA 5.15.17' },
  { deva: 'मन एव मनुष्याणां कारणं बन्धमोक्षयोः',
    en: 'The mind alone is the cause of bondage and of liberation.',
    gu: 'મન જ મનુષ્યનાં બંધન અને મોક્ષનું કારણ છે.',
    cite: 'AMṚTABINDU UPANIṢAD 2' },
  { deva: 'यत्र योगेश्वरः कृष्णो यत्र पार्थो धनुर्धरः',
    en: 'Where Kṛṣṇa is, and Arjuna the archer — there is fortune, there is victory.',
    gu: 'જ્યાં યોગેશ્વર કૃષ્ણ છે અને ધનુર્ધારી અર્જુન — ત્યાં જ શ્રી છે, ત્યાં જ વિજય.',
    cite: 'BHAGAVAD GĪTĀ 18.78' },
  { deva: 'ॐ पूर्णमदः पूर्णमिदं पूर्णात्पूर्णमुदच्यते',
    en: 'That is whole; this is whole; from the whole, the whole arises.',
    gu: 'તે પૂર્ણ છે; આ પૂર્ણ છે; પૂર્ણમાંથી પૂર્ણ પ્રગટે છે.',
    cite: 'ĪŚA UPANIṢAD · INVOCATION' },
  { deva: 'चरैवेति चरैवेति',
    en: 'Keep moving, keep moving on.',
    gu: 'ચાલતો રહે, ચાલતો જ રહે.',
    cite: 'AITAREYA BRĀHMAṆA 7.15' }
];
