/* ═══════════ Utsav Panchāng — festival calendar ═══════════
   Static date table, Aug 2026 → Dec 2027, verified against Drik Panchāng-family
   sources (Gujarati/amānta reckoning in the Gujarati labels). Tithi-based dates
   can shift by a day with locale; the calendar notes this. Refresh annually by
   appending the next year's rows — no code change needed. */
const FESTIVALS = [
  { d: '2026-08-28', en: 'Rakṣā Bandhan', gu: 'રક્ષાબંધન (બળેવ)', t_en: 'Śrāvaṇa Pūrṇimā', t_gu: 'શ્રાવણ સુદ પૂનમ',
    n_en: 'The bond of protection between brother and sister; also Baleva — the day of the sacred-thread renewal.',
    n_gu: 'ભાઈ-બહેન વચ્ચે રક્ષાનું બંધન; બળેવ એટલે જનોઈ બદલવાનો દિવસ પણ ખરો.' },
  { d: '2026-09-04', en: 'Janmāṣṭamī', gu: 'જન્માષ્ટમી', t_en: 'Śrāvaṇa Kṛṣṇa 8', t_gu: 'શ્રાવણ વદ આઠમ',
    n_en: 'The birth of Śrī Kṛṣṇa at midnight — fasting, kīrtan, and the midnight āratī.',
    n_gu: 'મધરાતે શ્રીકૃષ્ણનો જન્મ — ઉપવાસ, કીર્તન અને મધરાતની આરતી.' },
  { d: '2026-09-14', en: 'Gaṇeśa Chaturthī', gu: 'ગણેશ ચતુર્થી', t_en: 'Bhādrapada Śukla 4', t_gu: 'ભાદરવા સુદ ચોથ',
    n_en: 'Gaṇeśa is welcomed home; ten days of pūjā until the visarjan.',
    n_gu: 'ગણપતિનું ઘરે સ્વાગત; વિસર્જન સુધી દસ દિવસની પૂજા.' },
  { d: '2026-09-25', en: 'Anant Chaturdaśī', gu: 'અનંત ચૌદશ', t_en: 'Bhādrapada Śukla 14', t_gu: 'ભાદરવા સુદ ચૌદશ',
    n_en: 'Gaṇeśa visarjan — the clay returns to the water; Ananta (Viṣṇu) is worshipped.',
    n_gu: 'ગણેશ વિસર્જન — માટી પાણીમાં પાછી ફરે; અનંત (વિષ્ણુ)ની પૂજા.' },
  { d: '2026-09-27', en: 'Pitṛ Pakṣa begins', gu: 'પિતૃ પક્ષ (શ્રાદ્ધ) આરંભ', t_en: 'Śrāddha fortnight', t_gu: 'ભાદરવા વદ',
    n_en: 'A fortnight of remembering and honouring ancestors.',
    n_gu: 'પિતૃઓના સ્મરણ અને તર્પણનું પખવાડિયું.' },
  { d: '2026-10-11', en: 'Navarātri begins', gu: 'નવરાત્રી આરંભ', t_en: 'Āśvina Śukla 1 · Ghaṭasthāpanā', t_gu: 'આસો સુદ એકમ · ઘટસ્થાપના',
    n_en: 'Nine nights of the Goddess — garbā around the lit deep of the garbo.',
    n_gu: 'માતાજીની નવ રાત્રિ — ગરબાના દીવા ફરતે ઘૂમતા રાસ-ગરબા.' },
  { d: '2026-10-20', en: 'Vijayādaśamī (Dussehra)', gu: 'વિજયાદશમી (દશેરા)', t_en: 'Āśvina Śukla 10', t_gu: 'આસો સુદ દસમ',
    n_en: 'The victory of dharma — Rāma over Rāvaṇa, Durgā over Mahiṣāsura. Fāfḍā-jalebī day.',
    n_gu: 'ધર્મનો વિજય — રામનો રાવણ પર, દુર્ગાનો મહિષાસુર પર. ફાફડા-જલેબીનો દિવસ.' },
  { d: '2026-10-26', en: 'Śarad Pūrṇimā', gu: 'શરદ પૂનમ', t_en: 'Āśvina Pūrṇimā', t_gu: 'આસો સુદ પૂનમ',
    n_en: 'The year’s brightest moon; dūdh-pauā left in the moonlight.',
    n_gu: 'વર્ષની સૌથી તેજસ્વી પૂનમ; ચાંદનીમાં દૂધ-પૌંઆ.' },
  { d: '2026-10-29', en: 'Karvā Chauth', gu: 'કરવા ચોથ', t_en: 'Āśvina Kṛṣṇa 4 (Kārtika in pūrṇimānta)', t_gu: 'આસો વદ ચોથ (ઉત્તર ભારતમાં કારતક વદ ચોથ)',
    n_en: 'A North-Indian vrat for the spouse’s long life, now widely kept.',
    n_gu: 'પતિના દીર્ઘાયુ માટેનું ઉત્તર ભારતીય વ્રત, હવે વ્યાપકપણે પળાય છે.' },
  { d: '2026-11-06', en: 'Dhanteras', gu: 'ધનતેરસ', t_en: 'Āśvina Kṛṣṇa 13', t_gu: 'આસો વદ તેરસ',
    n_en: 'Dhanvantari and Lakṣmī honoured; new metal enters the house.',
    n_gu: 'ધન્વંતરિ અને લક્ષ્મીની પૂજા; ઘરમાં નવી ધાતુ આવે.' },
  { d: '2026-11-07', en: 'Kāḷī Chaudas', gu: 'કાળી ચૌદશ', t_en: 'Āśvina Kṛṣṇa 14', t_gu: 'આસો વદ ચૌદશ',
    n_en: 'Naraka Chaturdaśī — inner darkness is cleaned out before the lamps.',
    n_gu: 'નરક ચતુર્દશી — દીવા પહેલાં ભીતરનો અંધકાર સાફ થાય.' },
  { d: '2026-11-08', en: 'Dīvāḷī · Lakṣmī Pūjan', gu: 'દિવાળી · લક્ષ્મી પૂજન', t_en: 'Āśvina Amāvasyā', t_gu: 'આસો વદ અમાસ',
    n_en: 'The night of lamps; Lakṣmī pūjan and Chopḍā pūjan of the account books.',
    n_gu: 'દીવડાઓની રાત; લક્ષ્મી પૂજન અને ચોપડા પૂજન.' },
  { d: '2026-11-09', en: 'Bestu Varas · Annakūṭ', gu: 'બેસતું વર્ષ · અન્નકૂટ', t_en: 'Kārtika Śukla 1 · V.S. 2083', t_gu: 'કારતક સુદ એકમ · વિ.સં. ૨૦૮૩',
    n_en: 'Gujarati New Year — Vikram Samvat 2083 begins; Govardhan pūjā and the annakūṭ offering.',
    n_gu: 'નૂતન વર્ષાભિનંદન — વિક્રમ સંવત ૨૦૮૩નો આરંભ; ગોવર્ધન પૂજા અને અન્નકૂટ.' },
  { d: '2026-11-11', en: 'Bhāī Bīj', gu: 'ભાઈબીજ', t_en: 'Kārtika Śukla 2', t_gu: 'કારતક સુદ બીજ',
    n_en: 'Sisters welcome brothers; the Yama–Yamunā bond.',
    n_gu: 'બહેન ભાઈને આવકારે; યમ-યમુનાનું બંધન.' },
  { d: '2026-11-20', en: 'Dev Ūṭhī Ekādaśī · Tulsī Vivāh', gu: 'દેવઊઠી અગિયારસ · તુલસી વિવાહ', t_en: 'Kārtika Śukla 11', t_gu: 'કારતક સુદ અગિયારસ',
    n_en: 'Viṣṇu wakes from the cosmic sleep; the marriage season opens with Tulsī’s wedding.',
    n_gu: 'વિષ્ણુ યોગનિદ્રામાંથી જાગે; તુલસી વિવાહ સાથે લગ્નસરાની શરૂઆત.' },
  { d: '2026-11-24', en: 'Dev Dīvāḷī', gu: 'દેવ દિવાળી', t_en: 'Kārtika Pūrṇimā', t_gu: 'કારતક સુદ પૂનમ',
    n_en: 'The gods’ own Dīvāḷī — lamps on the rivers and ghats.',
    n_gu: 'દેવોની દિવાળી — નદી અને ઘાટ પર દીવા.' },
  { d: '2026-12-20', en: 'Gītā Jayantī', gu: 'ગીતા જયંતી', t_en: 'Mokṣadā Ekādaśī', t_gu: 'માગશર સુદ અગિયારસ',
    n_en: 'The day the Gītā was spoken at Kurukṣetra — read a chapter today.',
    n_gu: 'કુરુક્ષેત્રમાં ગીતા કહેવાયાનો દિવસ — આજે એક અધ્યાય વાંચો.' },

  { d: '2027-01-14', en: 'Uttarāyaṇ · Makar Saṅkrānti', gu: 'ઉત્તરાયણ · મકરસંક્રાંતિ', t_en: 'Sun enters Makara', t_gu: 'સૂર્ય મકર રાશિમાં',
    n_en: 'The sun turns north; kites over every Gujarati rooftop, til-guḷ and dān.',
    n_gu: 'સૂર્ય ઉત્તર તરફ વળે; અગાસીએ પતંગ, તલ-ગોળ અને દાન.' },
  { d: '2027-02-11', en: 'Vasant Panchamī', gu: 'વસંત પંચમી', t_en: 'Māgha Śukla 5', t_gu: 'મહા સુદ પાંચમ',
    n_en: 'Sarasvatī pūjan — spring, learning and the arts.',
    n_gu: 'સરસ્વતી પૂજન — વસંત, વિદ્યા અને કળા.' },
  { d: '2027-03-06', en: 'Mahā Śivarātri', gu: 'મહાશિવરાત્રી', t_en: 'Māgha Kṛṣṇa 14', t_gu: 'મહા વદ ચૌદશ',
    n_en: 'The great night of Śiva — fasting, night vigil, and the liṅga abhiṣek.',
    n_gu: 'શિવની મહાન રાત્રિ — ઉપવાસ, જાગરણ અને શિવલિંગ પર અભિષેક.' },
  { d: '2027-03-22', en: 'Hoḷī (Holikā Dahan)', gu: 'હોળી (હોલિકા દહન)', t_en: 'Phālguna Pūrṇimā', t_gu: 'ફાગણ સુદ પૂનમ',
    n_en: 'The bonfire of Holikā — Prahlāda’s faith outlives the fire.',
    n_gu: 'હોલિકા દહન — અગ્નિ પણ પ્રહ્લાદની શ્રદ્ધાને બાળી ન શક્યો.' },
  { d: '2027-03-23', en: 'Dhuḷeṭī', gu: 'ધુળેટી', t_en: 'Phālguna Kṛṣṇa 1', t_gu: 'ફાગણ વદ એકમ',
    n_en: 'The festival of colours, the morning after the fire.',
    n_gu: 'રંગોનો ઉત્સવ — હોળીની બીજી સવારે.' },
  { d: '2027-04-07', en: 'Chaitrī Navarātri begins', gu: 'ચૈત્રી નવરાત્રી આરંભ', t_en: 'Chaitra Śukla 1 · Guḍī Pāḍvā', t_gu: 'ચૈત્ર સુદ એકમ',
    n_en: 'The spring Navarātri opens the lunar new year (Guḍī Pāḍvā / Ugādi).',
    n_gu: 'વસંતની નવરાત્રી સાથે ચાંદ્ર નૂતન વર્ષનો આરંભ (ગુડી પડવો / ઉગાદિ).' },
  { d: '2027-04-15', en: 'Rāma Navamī', gu: 'રામનવમી', t_en: 'Chaitra Śukla 9', t_gu: 'ચૈત્ર સુદ નોમ',
    n_en: 'The birth of Śrī Rāma — dharma given a human face.',
    n_gu: 'શ્રીરામનો જન્મ — ધર્મનું માનવ સ્વરૂપ.' },
  { d: '2027-04-20', en: 'Hanumān Jayantī', gu: 'હનુમાન જયંતી', t_en: 'Chaitra Pūrṇimā', t_gu: 'ચૈત્ર સુદ પૂનમ',
    n_en: 'Strength perfected by devotion — the Hanumān Chālīsā day.',
    n_gu: 'ભક્તિથી પૂર્ણ થયેલું બળ — હનુમાન ચાલીસાનો દિવસ.' },
  { d: '2027-05-08', en: 'Akṣaya Tṛtīyā (Akhātrīj)', gu: 'અખાત્રીજ', t_en: 'Vaiśākha Śukla 3', t_gu: 'વૈશાખ સુદ ત્રીજ',
    n_en: 'The undiminishing day — auspicious for beginnings without consulting the muhūrta.',
    n_gu: 'અક્ષય દિવસ — વણજોયું મુહૂર્ત; શુભ આરંભ માટે ઉત્તમ.' },
  { d: '2027-07-05', en: 'Ratha Yātrā', gu: 'રથયાત્રા', t_en: 'Āṣāḍha Śukla 2', t_gu: 'અષાઢ સુદ બીજ',
    n_en: 'Jagannātha comes out to his people — Purī and Ahmedabad’s great processions.',
    n_gu: 'જગન્નાથજી નગરચર્યાએ નીકળે — પુરી અને અમદાવાદની ભવ્ય રથયાત્રા.' },
  { d: '2027-07-18', en: 'Guru Pūrṇimā', gu: 'ગુરુ પૂર્ણિમા', t_en: 'Āṣāḍha Pūrṇimā · Vyāsa Pūrṇimā', t_gu: 'અષાઢ સુદ પૂનમ · વ્યાસ પૂનમ',
    n_en: 'Gratitude to the guru-paramparā, from Vyāsa down to one’s own teachers.',
    n_gu: 'વ્યાસથી પોતાના ગુરુ સુધીની પરંપરાનું ઋણ-સ્મરણ.' },
  { d: '2027-08-17', en: 'Rakṣā Bandhan', gu: 'રક્ષાબંધન (બળેવ)', t_en: 'Śrāvaṇa Pūrṇimā', t_gu: 'શ્રાવણ સુદ પૂનમ',
    n_en: 'The bond of protection between brother and sister.',
    n_gu: 'ભાઈ-બહેન વચ્ચે રક્ષાનું બંધન.' },
  { d: '2027-08-25', en: 'Janmāṣṭamī', gu: 'જન્માષ્ટમી', t_en: 'Śrāvaṇa Kṛṣṇa 8', t_gu: 'શ્રાવણ વદ આઠમ',
    n_en: 'The birth of Śrī Kṛṣṇa at midnight.',
    n_gu: 'મધરાતે શ્રીકૃષ્ણનો જન્મ.' },
  { d: '2027-09-04', en: 'Gaṇeśa Chaturthī', gu: 'ગણેશ ચતુર્થી', t_en: 'Bhādrapada Śukla 4', t_gu: 'ભાદરવા સુદ ચોથ',
    n_en: 'Gaṇeśa is welcomed home.',
    n_gu: 'ગણપતિનું ઘરે સ્વાગત.' },
  { d: '2027-09-14', en: 'Anant Chaturdaśī', gu: 'અનંત ચૌદશ', t_en: 'Bhādrapada Śukla 14', t_gu: 'ભાદરવા સુદ ચૌદશ',
    n_en: 'Gaṇeśa visarjan — the clay returns to the water.',
    n_gu: 'ગણેશ વિસર્જન — માટી પાણીમાં પાછી ફરે.' },
  { d: '2027-09-16', en: 'Pitṛ Pakṣa begins', gu: 'પિતૃ પક્ષ (શ્રાદ્ધ) આરંભ', t_en: 'Śrāddha fortnight', t_gu: 'ભાદરવા વદ',
    n_en: 'A fortnight of remembering and honouring ancestors.',
    n_gu: 'પિતૃઓના સ્મરણ અને તર્પણનું પખવાડિયું.' },
  { d: '2027-09-30', en: 'Navarātri begins', gu: 'નવરાત્રી આરંભ', t_en: 'Āśvina Śukla 1 · Ghaṭasthāpanā', t_gu: 'આસો સુદ એકમ · ઘટસ્થાપના',
    n_en: 'Nine nights of the Goddess.',
    n_gu: 'માતાજીની નવ રાત્રિ.' },
  { d: '2027-10-09', en: 'Vijayādaśamī (Dussehra)', gu: 'વિજયાદશમી (દશેરા)', t_en: 'Āśvina Śukla 10', t_gu: 'આસો સુદ દસમ',
    n_en: 'The victory of dharma.',
    n_gu: 'ધર્મનો વિજય.' },
  { d: '2027-10-15', en: 'Śarad Pūrṇimā', gu: 'શરદ પૂનમ', t_en: 'Āśvina Pūrṇimā', t_gu: 'આસો સુદ પૂનમ',
    n_en: 'The year’s brightest moon.',
    n_gu: 'વર્ષની સૌથી તેજસ્વી પૂનમ.' },
  { d: '2027-10-18', en: 'Karvā Chauth', gu: 'કરવા ચોથ', t_en: 'Āśvina Kṛṣṇa 4 (Kārtika in pūrṇimānta)', t_gu: 'આસો વદ ચોથ (ઉત્તર ભારતમાં કારતક વદ ચોથ)',
    n_en: 'A North-Indian vrat for the spouse’s long life, now widely kept.',
    n_gu: 'પતિના દીર્ઘાયુ માટેનું ઉત્તર ભારતીય વ્રત, હવે વ્યાપકપણે પળાય છે.' },
  { d: '2027-10-27', en: 'Dhanteras', gu: 'ધનતેરસ', t_en: 'Āśvina Kṛṣṇa 13', t_gu: 'આસો વદ તેરસ',
    n_en: 'Dhanvantari and Lakṣmī honoured.',
    n_gu: 'ધન્વંતરિ અને લક્ષ્મીની પૂજા.' },
  { d: '2027-10-28', en: 'Kāḷī Chaudas', gu: 'કાળી ચૌદશ', t_en: 'Āśvina Kṛṣṇa 14', t_gu: 'આસો વદ ચૌદશ',
    n_en: 'Inner darkness is cleaned out before the lamps.',
    n_gu: 'દીવા પહેલાં ભીતરનો અંધકાર સાફ થાય.' },
  { d: '2027-10-29', en: 'Dīvāḷī · Lakṣmī Pūjan', gu: 'દિવાળી · લક્ષ્મી પૂજન', t_en: 'Āśvina Amāvasyā', t_gu: 'આસો વદ અમાસ',
    n_en: 'The night of lamps.',
    n_gu: 'દીવડાઓની રાત.' },
  { d: '2027-10-30', en: 'Bestu Varas · Annakūṭ', gu: 'બેસતું વર્ષ · અન્નકૂટ', t_en: 'Kārtika Śukla 1 · V.S. 2084', t_gu: 'કારતક સુદ એકમ · વિ.સં. ૨૦૮૪',
    n_en: 'Gujarati New Year — Vikram Samvat 2084 begins.',
    n_gu: 'નૂતન વર્ષાભિનંદન — વિક્રમ સંવત ૨૦૮૪નો આરંભ.' },
  { d: '2027-10-31', en: 'Bhāī Bīj', gu: 'ભાઈબીજ', t_en: 'Kārtika Śukla 2', t_gu: 'કારતક સુદ બીજ',
    n_en: 'Sisters welcome brothers.',
    n_gu: 'બહેન ભાઈને આવકારે.' },
  { d: '2027-11-10', en: 'Dev Ūṭhī Ekādaśī · Tulsī Vivāh', gu: 'દેવઊઠી અગિયારસ · તુલસી વિવાહ', t_en: 'Kārtika Śukla 11', t_gu: 'કારતક સુદ અગિયારસ',
    n_en: 'Viṣṇu wakes from the cosmic sleep; the marriage season opens.',
    n_gu: 'વિષ્ણુ યોગનિદ્રામાંથી જાગે; લગ્નસરાની શરૂઆત.' },
  { d: '2027-11-14', en: 'Dev Dīvāḷī', gu: 'દેવ દિવાળી', t_en: 'Kārtika Pūrṇimā', t_gu: 'કારતક સુદ પૂનમ',
    n_en: 'The gods’ own Dīvāḷī.',
    n_gu: 'દેવોની દિવાળી.' },
  { d: '2027-12-09', en: 'Gītā Jayantī', gu: 'ગીતા જયંતી', t_en: 'Mokṣadā Ekādaśī', t_gu: 'માગશર સુદ અગિયારસ',
    n_en: 'The day the Gītā was spoken — read a chapter today.',
    n_gu: 'ગીતા કહેવાયાનો દિવસ — આજે એક અધ્યાય વાંચો.' }
];
